#! /bin/sh

sxhkd &
compton --blur-background --backend glx --blur-kern 7x7box &
~/.fehbg &  # set wallpaper
pactl set-sink-volume 0 24% &  # set default volume
xfce4-panel -d &

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width         2
bspc config window_gap           6

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
